### ISSUE TITLE
Folder path is not a directory

### ISSUE THREAD

**Issue by nick1701d** [sketchbuch/vsc-workspace-sidebar#80] opened 2023-09-01 14:34 UTC
When I click the workspaces button in the sidebar, I get the error "Folder path is not a directory."
![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/46165671/edcaacee-fa6a-428b-9221-df5183cb8f98)

In the settings, I confirmed the path is correct and other settings appear to be fine:
![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/46165671/726badc6-8822-4948-a639-f5b77b8d2e73)

The path was copied directly from Windows File Explorer:
![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/46165671/98c093ac-277c-43d7-b295-eb288b633dfb)

I went into the security properties on the directory, and to be thorough, I granted "Everyone" read/write/execute/modify permissions:
![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/46165671/156eb696-9283-43e0-8461-74d2ef331ba3)

Do I need to format the path differently, or does it only work in certain Windows directories?

**Comment by sketchbuch** [comment] 2023-09-01 19:04
Hello, sorry you are having trouble.

Which version are you using?

`C:\Repos\VSCodeWorkspaces` is your folder path. Are the workspace files in this folder or in subfolders?

**Comment by sketchbuch** [comment] 2023-09-01 20:08
OK I see whereyour workspaces are. That should be fine. Maybe this is a windows issue. I shall test in a VM

**Comment by sketchbuch** [comment] 2023-09-02 20:09
@nick1701d Can you tell me which version you are using?

![working-windows-02-09-2023](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/16445037/6dcd71d1-040e-4697-a530-105929e5abda)

**Comment by nick1701d** [comment] 2023-09-05 00:37
Workspace Sidebar v1.5.1
VSCode v1.81.1
Windows 11 Pro v10.0.22621 Build 22621

**Comment by nick1701d** [comment] 2023-09-05 00:39
The workspace files are directly in that folder:  C:\Repos\VSCodeWorkspaces
They are not in any subdirectory of that folder.

**Comment by sketchbuch** [comment] 2023-09-11 06:46
I need to spend some time looking into this. Currently I can't reproduce it on Windows, in a VM evenrthing is running fine.

One more question, are both "Repos" and "VSCodeWorkspaces" normal folders? They are not symbolic links or junctions?

**Comment by sketchbuch** [comment] 2023-09-27 07:09
Currently I can't reproduce this, and if you are using 1.5.1 now only shows "is not a folder" if the path really isn't a folder.

I created the same folder and it worked fine. I will leave this issue open and will think about what I can do, but until I can reproduce it I can't fix it. Sorry!

**Comment by sketchbuch** [comment] 2024-03-20 07:37
Closing as roofFolders are now completely different

**Closed by sketchbuch** 2024-03-20 07:37 UTC
Labels: bug, feedback needed, analysis, windows, can't reproduce
